const ScreensName = {
  HOME: "Home",
  WELCOME: "Welcome",
  SIGNIN: "SignIn",
  PARENTPROFILENFO: "ParentProfileInfo",
  LEARNER_QUESTIONAIR: "LearnerQuestionair",
  ACCOUNT: "Account",
  MAGICBACKPACK: "MagicBackpackScreen",
  QUESTIONAIRE: "Questionnaire",
  AILIVESECTION: "AiLiveSession",
  ADDCHILD: "AddChild",
  CREATECHILDPROFILE: "CreateChildProfile",
  STARTQUESTIONAIRE: "StartQuestionaire",
  PARENTQUESTIONAIRE: "ParentQuestionaire",
  GENERATECHILD: "GenerateChild",
  AILIVEVEDIOSECTION: "AiLiveVedio",
  AILIVEQUESTIONAIR: "AiLiveQuestion",
  AILIVEEXAMPLE: "AiLiveExample",
  AIGAME: "AIGAME",
  COACHACCOUNT: "CoachAccount",
  APPLICATIONSTATUS: "ApplicationStatus",
  DIGITALCONTRACT: "DigitalContract",
  PAYOUTSETUP: "PayoutSetup",
  TRAINING: "Training",
  STARTTRAINING: "StartTraining",
  STARTQUIZ: "StartQuiz",
  QUIZ: "Quiz",
  ASSIGNMENT: "Assignment",
  CERTIFICATION: "Certification",
};
export default ScreensName;
